services:
    deuzu.request_collector.collector.dispatcher:
        class: Deuzu\RequestCollectorBundle\Collector\DispatcherCollector
        calls:
            - ["setLoggerCollector", ["@?deuzu.request_collector.collector.logger"]]
            - ["setPersisterCollector", ["@?deuzu.request_collector.collector.persister"]]
            - ["setMailerCollector", ["@?deuzu.request_collector.collector.mailer"]]

    deuzu.request_collector.collector.logger:
        class: Deuzu\RequestCollectorBundle\Collector\LoggerCollector
        arguments:
            - "@serializer"
            - "@deuzu.request_collector.logger.container"
            - "@logger" # deprecated
            - "%kernel.logs_dir%"
            - "%kernel.environment%"
        tags:
            - { name: monolog.logger, channel: main }

    deuzu.request_collector.collector.persister:
        class: Deuzu\RequestCollectorBundle\Collector\PersisterCollector
        arguments:
            - "@doctrine"

    deuzu.request_collector.collector.mailer:
        class: Deuzu\RequestCollectorBundle\Collector\MailerCollector
        arguments:
            - "@swiftmailer.mailer.default"
            - "@templating"
            - "%deuzu_request_collector%"
